services:
  - type: web
    name: cryptodashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash render_start.sh
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: dashboard.settings_production
      - key: SECRET_KEY
        generateValue: true
      - key: NEWS_API_KEY
        value: ca1a1a52ccf34249b58683097d803fda
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.13"
      - key: DATABASE_URL
        fromDatabase:
          name: cryptodashboard-db
          property: connectionString

databases:
  - name: cryptodashboard-db
    databaseName: cryptodashboard
    user: cryptouser