# Generated by Django 5.2.6 on 2025-09-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price_change_24h',
            field=models.FloatField(default=0.0),
        ),
    ]
