# Generated by Django 5.2.6 on 2025-09-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_coin_price_change_24h'),
    ]

    operations = [
    ]
