# Generated by Django 5.2.6 on 2025-09-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_portfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
