# Generated by Django 5.2.6 on 2025-09-27 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_portfolio_date_added_portfolio_last_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_invested',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['market_cap'], name='market_coin_market__cf2762_idx'),
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['symbol'], name='market_coin_symbol_7c1732_idx'),
        ),
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['current_price'], name='market_coin_current_7c64c0_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'total_invested'], name='market_port_user_id_247823_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['last_updated'], name='market_port_last_up_5ef3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'coin'], name='market_watc_user_id_613f59_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['date_added'], name='market_watc_date_ad_4794ff_idx'),
        ),
    ]
